name: Setup Node.js Composite Action
description: 'Node.jsのバージョンを指定してNode.jsをセットアップするComposite Action'

inputs:
  node-version-file:
    description: 'Node.jsのバージョンが記述されたファイル'
    required: true
    default: '.node-version'

runs:
  using: 'composite'
  steps:
    - name: Node.jsの構築
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: pnpmの有効化
      shell: bash
      run: corepack enable

    - name: ライブラリのインストール
      shell: bash
      working-directory: ${{ github.workspace }}/application
      run: pnpm install --frozen-lockfile

    - name: Prismaクライアントの生成
      shell: bash
      working-directory: ${{ github.workspace }}/application
      run: pnpm run setup
