name: Setup Node.js Composite Action
description: 'Node.jsのバージョンを指定してNode.jsをセットアップするComposite Action'

inputs:
  node-version-file:
    description: 'Node.jsのバージョンが記述されたファイル'
    required: true
    default: '.node-version'

runs:
  using: 'composite'
  steps:
    - name: pnpmのセットアップ
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

    - name: Node.jsの構築
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: ライブラリのインストール
      shell: bash
      run: pnpm install --frozen-lockfile
