name: CD
description: Continuous Delivery

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 対象リソース
        required: true
        default: web
        type: choice
        options:
          - web
          - database

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./application

jobs:
  web:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || github.event.inputs.deploy_type == 'web' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: .node-version

      - name: ビルド
        run: pnpm run build

      - name: デプロイ
        id: deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./application/packages/web
          command: deploy
          # Secretsで保存するものをActionsで管理し、環境変数として渡す
          secrets: |
            SUPABASE_URL
            SUPABASE_ANON_KEY
            DISCORD_WEBHOOK_URL
        env:
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: デプロイの出力を表示
        env:
          CMD_OUTPUT: ${{ steps.deploy.outputs.command-output }}
        run: echo $CMD_OUTPUT

  database:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || github.event.inputs.deploy_type == 'database' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: .node-version

      - name: D1のマイグレーション適用
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./application/packages/web
          command: d1 migrations apply trend-diary-db --remote
