name: Cron Test

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/cron-test.yaml'
      - '.github/workflows/cron-deploy.yaml'
      - '.github/actions/setup_node/action.yaml'
      - 'application/wrangler.cron.toml'
      - 'application/package.json'
      - 'application/pnpm-lock.yaml'
      - 'application/src/cron/**'
      - 'application/packages/common/**'
      - 'application/packages/datastore/**'
      - 'application/packages/domain/**'
      - 'application/packages/notification/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cron-test.yaml'
      - '.github/workflows/cron-deploy.yaml'
      - '.github/actions/setup_node/action.yaml'
      - 'application/wrangler.cron.toml'
      - 'application/package.json'
      - 'application/pnpm-lock.yaml'
      - 'application/src/cron/**'
      - 'application/packages/common/**'
      - 'application/packages/datastore/**'
      - 'application/packages/domain/**'
      - 'application/packages/notification/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./application

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: .node-version

      - name: Cronテスト
        run: pnpm run test:cron
