name: Lint

on:
  push:

permissions:
  contents: read
  pull-requests: write

# 共通の設定を定義
env:
  NODE_VERSION_FILE: .node-version
  BIOME_VERSION: 2.0.6

defaults:
  run:
    shell: bash
    working-directory: ./application

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Biome
        uses: biomejs/setup-biome@a05c02a1304287da45f13648675a70d5841acdbc # v2
        with:
          version: ${{ env.BIOME_VERSION }}

      - name: Run Biome CI
        run: biome ci .

  # 本来であれば、概念的にコンパイルはLint/Formatと同列ではないが、実行時間短縮のために並列実行にしている
  ts-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: TypeScript型チェック
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: ビルド
        run: pnpm run build
