name: Check Prisma Schema
description: 'Prismaのスキーマファイルが正しい形式であるかを検証します'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.prisma'
      - '.github/workflows/prisma.yaml'

permissions:
  contents: read

env:
  NODE_VERSION_FILE: .node-version

defaults:
  run:
    shell: bash
    working-directory: ./application

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: Prismaファイルの検証
        run: npx prisma format --check
